; Melange build of lib/foundation. Same sources, copied rather than duplicated.

(copy_files#
 (files ../../../lib/foundation/*.ml))

(copy_files#
 (files ../../../lib/foundation/*.mli))

(library
 (name foundation)
 (modes byte native melange)
 (libraries fmt)
 (enabled_if
  (= %{env:ASM_MELANGE=false} true)))
