(* Generated by [compcert_tools isa-table riscv-emit] from the committed riscv-opcodes
   exports (isa-db/export/riscv_opcodes); do not edit by hand. The selection and field
   domains are Isa_riscv_table's DEC-RV-TABLE rule. *)

open Riscv_table_row

let rows : row array =
  [|
    {
      mnemonic = "sret";
      mask = 0xffffffffL;
      match_ = 0x10200073L;
      operands = [  ];
      xlen = 0;
      feature = "s";
      source = "rv_s/sret";
    };
    {
      mnemonic = "dret";
      mask = 0xffffffffL;
      match_ = 0x7b200073L;
      operands = [  ];
      xlen = 0;
      feature = "sdext";
      source = "rv_sdext/dret";
    };
    {
      mnemonic = "sctrclr";
      mask = 0xffffffffL;
      match_ = 0x10400073L;
      operands = [  ];
      xlen = 0;
      feature = "ssctr";
      source = "rv_ssctr/sctrclr";
    };
    {
      mnemonic = "sfence.inval.ir";
      mask = 0xffffffffL;
      match_ = 0x18100073L;
      operands = [  ];
      xlen = 0;
      feature = "svinval";
      source = "rv_svinval/sfence.inval.ir";
    };
    {
      mnemonic = "sfence.w.inval";
      mask = 0xffffffffL;
      match_ = 0x18000073L;
      operands = [  ];
      xlen = 0;
      feature = "svinval";
      source = "rv_svinval/sfence.w.inval";
    };
    {
      mnemonic = "mret";
      mask = 0xffffffffL;
      match_ = 0x30200073L;
      operands = [  ];
      xlen = 0;
      feature = "system";
      source = "rv_system/mret";
    };
    {
      mnemonic = "wfi";
      mask = 0xffffffffL;
      match_ = 0x10500073L;
      operands = [  ];
      xlen = 0;
      feature = "system";
      source = "rv_system/wfi";
    };
    {
      mnemonic = "wrs.nto";
      mask = 0xffffffffL;
      match_ = 0xd00073L;
      operands = [  ];
      xlen = 0;
      feature = "zawrs";
      source = "rv_zawrs/wrs.nto";
    };
    {
      mnemonic = "wrs.sto";
      mask = 0xffffffffL;
      match_ = 0x1d00073L;
      operands = [  ];
      xlen = 0;
      feature = "zawrs";
      source = "rv_zawrs/wrs.sto";
    };
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc0c073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x1";
    };
    {
      mnemonic = "sspopchk";
      mask = 0xffffffffL;
      match_ = 0xcdc2c073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspopchk.x5";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce104073L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x1";
    };
    {
      mnemonic = "sspush";
      mask = 0xffffffffL;
      match_ = 0xce504073L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/sspush.x5";
    };
    {
      mnemonic = "ntl.all";
      mask = 0xffffffffL;
      match_ = 0x500033L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_zihintntl/ntl.all";
    };
    {
      mnemonic = "ntl.p1";
      mask = 0xffffffffL;
      match_ = 0x200033L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_zihintntl/ntl.p1";
    };
    {
      mnemonic = "ntl.pall";
      mask = 0xffffffffL;
      match_ = 0x300033L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_zihintntl/ntl.pall";
    };
    {
      mnemonic = "ntl.s1";
      mask = 0xffffffffL;
      match_ = 0x400033L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_zihintntl/ntl.s1";
    };
    {
      mnemonic = "frcsr";
      mask = 0xfffff07fL;
      match_ = 0x302073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frcsr";
    };
    {
      mnemonic = "frflags";
      mask = 0xfffff07fL;
      match_ = 0x102073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frflags";
    };
    {
      mnemonic = "frrm";
      mask = 0xfffff07fL;
      match_ = 0x202073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/frrm";
    };
    {
      mnemonic = "cbo.clean";
      mask = 0xfff07fffL;
      match_ = 0x10200fL;
      operands = [ Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicbom";
      source = "rv_zicbo/cbo.clean";
    };
    {
      mnemonic = "cbo.flush";
      mask = 0xfff07fffL;
      match_ = 0x20200fL;
      operands = [ Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicbom";
      source = "rv_zicbo/cbo.flush";
    };
    {
      mnemonic = "cbo.inval";
      mask = 0xfff07fffL;
      match_ = 0x200fL;
      operands = [ Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicbom";
      source = "rv_zicbo/cbo.inval";
    };
    {
      mnemonic = "cbo.zero";
      mask = 0xfff07fffL;
      match_ = 0x40200fL;
      operands = [ Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicboz";
      source = "rv_zicbo/cbo.zero";
    };
    {
      mnemonic = "ssrdp";
      mask = 0xfffff07fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = true } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssrdp";
    };
    {
      mnemonic = "rdcycle";
      mask = 0xfffff07fL;
      match_ = 0xc0002073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "zicntr";
      source = "rv_zicntr/rdcycle";
    };
    {
      mnemonic = "rdinstret";
      mask = 0xfffff07fL;
      match_ = 0xc0202073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "zicntr";
      source = "rv_zicntr/rdinstret";
    };
    {
      mnemonic = "rdtime";
      mask = 0xfffff07fL;
      match_ = 0xc0102073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 0;
      feature = "zicntr";
      source = "rv_zicntr/rdtime";
    };
    {
      mnemonic = "rdcycleh";
      mask = 0xfffff07fL;
      match_ = 0xc8002073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 32;
      feature = "zicntr";
      source = "rv32_zicntr/rdcycleh";
    };
    {
      mnemonic = "rdinstreth";
      mask = 0xfffff07fL;
      match_ = 0xc8202073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 32;
      feature = "zicntr";
      source = "rv32_zicntr/rdinstreth";
    };
    {
      mnemonic = "rdtimeh";
      mask = 0xfffff07fL;
      match_ = 0xc8102073L;
      operands = [ Gpr { lsb = 7; nonzero = false } ];
      xlen = 32;
      feature = "zicntr";
      source = "rv32_zicntr/rdtimeh";
    };
    {
      mnemonic = "fmv.d.x";
      mask = 0xfff0707fL;
      match_ = 0xf2000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "d";
      source = "rv64_d/fmv.d.x";
    };
    {
      mnemonic = "hlv.d";
      mask = 0xfff0707fL;
      match_ = 0x6c004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "h";
      source = "rv64_h/hlv.d";
    };
    {
      mnemonic = "hlv.wu";
      mask = 0xfff0707fL;
      match_ = 0x68104073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "h";
      source = "rv64_h/hlv.wu";
    };
    {
      mnemonic = "hsv.d";
      mask = 0xfe007fffL;
      match_ = 0x6e004073L;
      operands = [ Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "h";
      source = "rv64_h/hsv.d";
    };
    {
      mnemonic = "fmvh.x.q";
      mask = 0xfff0707fL;
      match_ = 0xe6100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 64;
      feature = "zfa";
      source = "rv64_q_zfa/fmvh.x.q";
    };
    {
      mnemonic = "zext.w";
      mask = 0xfff0707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/zext.w";
    };
    {
      mnemonic = "fcvtmod.w.d";
      mask = 0xfff0707fL;
      match_ = 0xc2801053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Keyword "rtz" ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fcvtmod.w.d";
    };
    {
      mnemonic = "fli.d";
      mask = 0xfff0707fL;
      match_ = 0xf2100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fli.d";
    };
    {
      mnemonic = "fscsr";
      mask = 0xfff0707fL;
      match_ = 0x301073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fscsr";
    };
    {
      mnemonic = "fsflags";
      mask = 0xfff0707fL;
      match_ = 0x101073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflags";
    };
    {
      mnemonic = "fsflagsi";
      mask = 0xfff0707fL;
      match_ = 0x105073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsflagsi";
    };
    {
      mnemonic = "fsrm";
      mask = 0xfff0707fL;
      match_ = 0x201073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrm";
    };
    {
      mnemonic = "fsrmi";
      mask = 0xfff0707fL;
      match_ = 0x205073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Uimm { lsb = 15; width = 5 } ];
      xlen = 0;
      feature = "f";
      source = "rv_f/fsrmi";
    };
    {
      mnemonic = "fli.s";
      mask = 0xfff0707fL;
      match_ = 0xf0100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fli.s";
    };
    {
      mnemonic = "hfence.gvma";
      mask = 0xfe007fffL;
      match_ = 0x62000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hfence.gvma";
    };
    {
      mnemonic = "hfence.vvma";
      mask = 0xfe007fffL;
      match_ = 0x22000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hfence.vvma";
    };
    {
      mnemonic = "hlv.b";
      mask = 0xfff0707fL;
      match_ = 0x60004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlv.b";
    };
    {
      mnemonic = "hlv.bu";
      mask = 0xfff0707fL;
      match_ = 0x60104073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlv.bu";
    };
    {
      mnemonic = "hlv.h";
      mask = 0xfff0707fL;
      match_ = 0x64004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlv.h";
    };
    {
      mnemonic = "hlv.hu";
      mask = 0xfff0707fL;
      match_ = 0x64104073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlv.hu";
    };
    {
      mnemonic = "hlv.w";
      mask = 0xfff0707fL;
      match_ = 0x68004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlv.w";
    };
    {
      mnemonic = "hlvx.hu";
      mask = 0xfff0707fL;
      match_ = 0x64304073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlvx.hu";
    };
    {
      mnemonic = "hlvx.wu";
      mask = 0xfff0707fL;
      match_ = 0x68304073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hlvx.wu";
    };
    {
      mnemonic = "hsv.b";
      mask = 0xfe007fffL;
      match_ = 0x62004073L;
      operands = [ Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hsv.b";
    };
    {
      mnemonic = "hsv.h";
      mask = 0xfe007fffL;
      match_ = 0x66004073L;
      operands = [ Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hsv.h";
    };
    {
      mnemonic = "hsv.w";
      mask = 0xfe007fffL;
      match_ = 0x6a004073L;
      operands = [ Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "h";
      source = "rv_h/hsv.w";
    };
    {
      mnemonic = "fclass.q";
      mask = 0xfff0707fL;
      match_ = 0xe6001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fclass.q";
    };
    {
      mnemonic = "fli.q";
      mask = 0xfff0707fL;
      match_ = 0xf6100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fli.q";
    };
    {
      mnemonic = "sfence.vma";
      mask = 0xfe007fffL;
      match_ = 0x12000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "s";
      source = "rv_s/sfence.vma";
    };
    {
      mnemonic = "sinval.vma";
      mask = 0xfe007fffL;
      match_ = 0x16000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "svinval";
      source = "rv_svinval/sinval.vma";
    };
    {
      mnemonic = "hinval.gvma";
      mask = 0xfe007fffL;
      match_ = 0x66000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "svinval";
      source = "rv_svinval_h/hinval.gvma";
    };
    {
      mnemonic = "hinval.vvma";
      mask = 0xfe007fffL;
      match_ = 0x26000073L;
      operands = [ Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "svinval";
      source = "rv_svinval_h/hinval.vvma";
    };
    {
      mnemonic = "fclass.h";
      mask = 0xfff0707fL;
      match_ = 0xe4001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fclass.h";
    };
    {
      mnemonic = "fli.h";
      mask = 0xfff0707fL;
      match_ = 0xf4100053L;
      operands = [ Fpr { lsb = 7 }; Fli { lsb = 15 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fli.h";
    };
    {
      mnemonic = "fmv.h.x";
      mask = 0xfff0707fL;
      match_ = 0xf4000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fmv.h.x";
    };
    {
      mnemonic = "fmv.x.h";
      mask = 0xfff0707fL;
      match_ = 0xe4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fmv.x.h";
    };
    {
      mnemonic = "mop.r.0";
      mask = 0xfff0707fL;
      match_ = 0x81c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.0";
    };
    {
      mnemonic = "mop.r.10";
      mask = 0xfff0707fL;
      match_ = 0x89e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.10";
    };
    {
      mnemonic = "mop.r.11";
      mask = 0xfff0707fL;
      match_ = 0x89f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.11";
    };
    {
      mnemonic = "mop.r.12";
      mask = 0xfff0707fL;
      match_ = 0x8dc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.12";
    };
    {
      mnemonic = "mop.r.13";
      mask = 0xfff0707fL;
      match_ = 0x8dd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.13";
    };
    {
      mnemonic = "mop.r.14";
      mask = 0xfff0707fL;
      match_ = 0x8de04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.14";
    };
    {
      mnemonic = "mop.r.15";
      mask = 0xfff0707fL;
      match_ = 0x8df04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.15";
    };
    {
      mnemonic = "mop.r.16";
      mask = 0xfff0707fL;
      match_ = 0xc1c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.16";
    };
    {
      mnemonic = "mop.r.17";
      mask = 0xfff0707fL;
      match_ = 0xc1d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.17";
    };
    {
      mnemonic = "mop.r.18";
      mask = 0xfff0707fL;
      match_ = 0xc1e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.18";
    };
    {
      mnemonic = "mop.r.19";
      mask = 0xfff0707fL;
      match_ = 0xc1f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.19";
    };
    {
      mnemonic = "mop.r.1";
      mask = 0xfff0707fL;
      match_ = 0x81d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.1";
    };
    {
      mnemonic = "mop.r.20";
      mask = 0xfff0707fL;
      match_ = 0xc5c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.20";
    };
    {
      mnemonic = "mop.r.21";
      mask = 0xfff0707fL;
      match_ = 0xc5d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.21";
    };
    {
      mnemonic = "mop.r.22";
      mask = 0xfff0707fL;
      match_ = 0xc5e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.22";
    };
    {
      mnemonic = "mop.r.23";
      mask = 0xfff0707fL;
      match_ = 0xc5f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.23";
    };
    {
      mnemonic = "mop.r.24";
      mask = 0xfff0707fL;
      match_ = 0xc9c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.24";
    };
    {
      mnemonic = "mop.r.25";
      mask = 0xfff0707fL;
      match_ = 0xc9d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.25";
    };
    {
      mnemonic = "mop.r.26";
      mask = 0xfff0707fL;
      match_ = 0xc9e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.26";
    };
    {
      mnemonic = "mop.r.27";
      mask = 0xfff0707fL;
      match_ = 0xc9f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.27";
    };
    {
      mnemonic = "mop.r.28";
      mask = 0xfff0707fL;
      match_ = 0xcdc04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.28";
    };
    {
      mnemonic = "mop.r.29";
      mask = 0xfff0707fL;
      match_ = 0xcdd04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.29";
    };
    {
      mnemonic = "mop.r.2";
      mask = 0xfff0707fL;
      match_ = 0x81e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.2";
    };
    {
      mnemonic = "mop.r.30";
      mask = 0xfff0707fL;
      match_ = 0xcde04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.30";
    };
    {
      mnemonic = "mop.r.31";
      mask = 0xfff0707fL;
      match_ = 0xcdf04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.31";
    };
    {
      mnemonic = "mop.r.3";
      mask = 0xfff0707fL;
      match_ = 0x81f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.3";
    };
    {
      mnemonic = "mop.r.4";
      mask = 0xfff0707fL;
      match_ = 0x85c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.4";
    };
    {
      mnemonic = "mop.r.5";
      mask = 0xfff0707fL;
      match_ = 0x85d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.5";
    };
    {
      mnemonic = "mop.r.6";
      mask = 0xfff0707fL;
      match_ = 0x85e04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.6";
    };
    {
      mnemonic = "mop.r.7";
      mask = 0xfff0707fL;
      match_ = 0x85f04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.7";
    };
    {
      mnemonic = "mop.r.8";
      mask = 0xfff0707fL;
      match_ = 0x89c04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.8";
    };
    {
      mnemonic = "mop.r.9";
      mask = 0xfff0707fL;
      match_ = 0x89d04073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.r.9";
    };
    {
      mnemonic = "fmvh.x.d";
      mask = 0xfff0707fL;
      match_ = 0xe2100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 } ];
      xlen = 32;
      feature = "zfa";
      source = "rv32_d_zfa/fmvh.x.d";
    };
    {
      mnemonic = "prefetch.i";
      mask = 0x1f07fffL;
      match_ = 0x6013L;
      operands = [ Mem_hi { base = 15 } ];
      xlen = 0;
      feature = "zicbop";
      source = "rv_zicbo/prefetch.i";
    };
    {
      mnemonic = "prefetch.r";
      mask = 0x1f07fffL;
      match_ = 0x106013L;
      operands = [ Mem_hi { base = 15 } ];
      xlen = 0;
      feature = "zicbop";
      source = "rv_zicbo/prefetch.r";
    };
    {
      mnemonic = "prefetch.w";
      mask = 0x1f07fffL;
      match_ = 0x306013L;
      operands = [ Mem_hi { base = 15 } ];
      xlen = 0;
      feature = "zicbop";
      source = "rv_zicbo/prefetch.w";
    };
    {
      mnemonic = "fcvt.l.q";
      mask = 0xfff0007fL;
      match_ = 0xc6200053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.l.q";
    };
    {
      mnemonic = "fcvt.lu.q";
      mask = 0xfff0007fL;
      match_ = 0xc6300053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.lu.q";
    };
    {
      mnemonic = "fcvt.q.l";
      mask = 0xfff0007fL;
      match_ = 0xd6200053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.q.l";
    };
    {
      mnemonic = "fcvt.q.lu";
      mask = 0xfff0007fL;
      match_ = 0xd6300053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 64;
      feature = "q";
      source = "rv64_q/fcvt.q.lu";
    };
    {
      mnemonic = "fcvt.h.l";
      mask = 0xfff0007fL;
      match_ = 0xd4200053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.h.l";
    };
    {
      mnemonic = "fcvt.h.lu";
      mask = 0xfff0007fL;
      match_ = 0xd4300053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.h.lu";
    };
    {
      mnemonic = "fcvt.l.h";
      mask = 0xfff0007fL;
      match_ = 0xc4200053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.l.h";
    };
    {
      mnemonic = "fcvt.lu.h";
      mask = 0xfff0007fL;
      match_ = 0xc4300053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 64;
      feature = "zfh";
      source = "rv64_zfh/fcvt.lu.h";
    };
    {
      mnemonic = "fround.d";
      mask = 0xfff0007fL;
      match_ = 0x42400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fround.d";
    };
    {
      mnemonic = "froundnx.d";
      mask = 0xfff0007fL;
      match_ = 0x42500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/froundnx.d";
    };
    {
      mnemonic = "fcvt.d.h";
      mask = 0xfff0007fL;
      match_ = 0x42200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_d_zfhmin/fcvt.d.h";
    };
    {
      mnemonic = "fcvt.h.d";
      mask = 0xfff0007fL;
      match_ = 0x44100053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_d_zfhmin/fcvt.h.d";
    };
    {
      mnemonic = "fround.s";
      mask = 0xfff0007fL;
      match_ = 0x40400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fround.s";
    };
    {
      mnemonic = "froundnx.s";
      mask = 0xfff0007fL;
      match_ = 0x40500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/froundnx.s";
    };
    {
      mnemonic = "fcvt.d.q";
      mask = 0xfff0007fL;
      match_ = 0x42300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.d.q";
    };
    {
      mnemonic = "fcvt.q.d";
      mask = 0xfff0007fL;
      match_ = 0x46100053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.d";
    };
    {
      mnemonic = "fcvt.q.s";
      mask = 0xfff0007fL;
      match_ = 0x46000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.s";
    };
    {
      mnemonic = "fcvt.q.w";
      mask = 0xfff0007fL;
      match_ = 0xd6000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.w";
    };
    {
      mnemonic = "fcvt.q.wu";
      mask = 0xfff0007fL;
      match_ = 0xd6100053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.q.wu";
    };
    {
      mnemonic = "fcvt.s.q";
      mask = 0xfff0007fL;
      match_ = 0x40300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.s.q";
    };
    {
      mnemonic = "fcvt.w.q";
      mask = 0xfff0007fL;
      match_ = 0xc6000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.w.q";
    };
    {
      mnemonic = "fcvt.wu.q";
      mask = 0xfff0007fL;
      match_ = 0xc6100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fcvt.wu.q";
    };
    {
      mnemonic = "fsqrt.q";
      mask = 0xfff0007fL;
      match_ = 0x5e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsqrt.q";
    };
    {
      mnemonic = "fround.q";
      mask = 0xfff0007fL;
      match_ = 0x46400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fround.q";
    };
    {
      mnemonic = "froundnx.q";
      mask = 0xfff0007fL;
      match_ = 0x46500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/froundnx.q";
    };
    {
      mnemonic = "fcvt.h.q";
      mask = 0xfff0007fL;
      match_ = 0x44300053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_q_zfhmin/fcvt.h.q";
    };
    {
      mnemonic = "fcvt.q.h";
      mask = 0xfff0007fL;
      match_ = 0x46200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_q_zfhmin/fcvt.q.h";
    };
    {
      mnemonic = "fcvt.bf16.s";
      mask = 0xfff0007fL;
      match_ = 0x44800053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfbfmin";
      source = "rv_zfbfmin/fcvt.bf16.s";
    };
    {
      mnemonic = "fcvt.s.bf16";
      mask = 0xfff0007fL;
      match_ = 0x40600053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfbfmin";
      source = "rv_zfbfmin/fcvt.s.bf16";
    };
    {
      mnemonic = "fcvt.h.w";
      mask = 0xfff0007fL;
      match_ = 0xd4000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.h.w";
    };
    {
      mnemonic = "fcvt.h.wu";
      mask = 0xfff0007fL;
      match_ = 0xd4100053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.h.wu";
    };
    {
      mnemonic = "fcvt.w.h";
      mask = 0xfff0007fL;
      match_ = 0xc4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.w.h";
    };
    {
      mnemonic = "fcvt.wu.h";
      mask = 0xfff0007fL;
      match_ = 0xc4100053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fcvt.wu.h";
    };
    {
      mnemonic = "fsqrt.h";
      mask = 0xfff0007fL;
      match_ = 0x5c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsqrt.h";
    };
    {
      mnemonic = "fround.h";
      mask = 0xfff0007fL;
      match_ = 0x44400053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fround.h";
    };
    {
      mnemonic = "froundnx.h";
      mask = 0xfff0007fL;
      match_ = 0x44500053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/froundnx.h";
    };
    {
      mnemonic = "fcvt.h.s";
      mask = 0xfff0007fL;
      match_ = 0x44000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fcvt.h.s";
    };
    {
      mnemonic = "fcvt.s.h";
      mask = 0xfff0007fL;
      match_ = 0x40200053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Rm { lsb = 12; default = 0 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fcvt.s.h";
    };
    {
      mnemonic = "fabs.q";
      mask = 0xfe00707fL;
      match_ = 0x26002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fabs.q";
    };
    {
      mnemonic = "fmv.q";
      mask = 0xfe00707fL;
      match_ = 0x26000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmv.q";
    };
    {
      mnemonic = "fneg.q";
      mask = 0xfe00707fL;
      match_ = 0x26001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fneg.q";
    };
    {
      mnemonic = "fabs.h";
      mask = 0xfe00707fL;
      match_ = 0x24002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fabs.h";
    };
    {
      mnemonic = "fmv.h";
      mask = 0xfe00707fL;
      match_ = 0x24000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmv.h";
    };
    {
      mnemonic = "fneg.h";
      mask = 0xfe00707fL;
      match_ = 0x24001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Tied { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fneg.h";
    };
    {
      mnemonic = "fmvp.q.x";
      mask = 0xfe00707fL;
      match_ = 0xb6000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 64;
      feature = "zfa";
      source = "rv64_q_zfa/fmvp.q.x";
    };
    {
      mnemonic = "amocas.q";
      mask = 0xfe00707fL;
      match_ = 0x2800402fL;
      operands = [ Gpr_pair { lsb = 7; below = 128 }; Gpr_pair { lsb = 20; below = 128 }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "zacas";
      source = "rv64_zacas/amocas.q";
    };
    {
      mnemonic = "amocas.q.aq";
      mask = 0xfe00707fL;
      match_ = 0x2c00402fL;
      operands = [ Gpr_pair { lsb = 7; below = 128 }; Gpr_pair { lsb = 20; below = 128 }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "zacas";
      source = "rv64_zacas/amocas.q";
    };
    {
      mnemonic = "amocas.q.rl";
      mask = 0xfe00707fL;
      match_ = 0x2a00402fL;
      operands = [ Gpr_pair { lsb = 7; below = 128 }; Gpr_pair { lsb = 20; below = 128 }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "zacas";
      source = "rv64_zacas/amocas.q";
    };
    {
      mnemonic = "amocas.q.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2e00402fL;
      operands = [ Gpr_pair { lsb = 7; below = 128 }; Gpr_pair { lsb = 20; below = 128 }; Mem_zero { base = 15 } ];
      xlen = 64;
      feature = "zacas";
      source = "rv64_zacas/amocas.q";
    };
    {
      mnemonic = "add.uw";
      mask = 0xfe00707fL;
      match_ = 0x800003bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/add.uw";
    };
    {
      mnemonic = "fleq.d";
      mask = 0xfe00707fL;
      match_ = 0xa2004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fleq.d";
    };
    {
      mnemonic = "fltq.d";
      mask = 0xfe00707fL;
      match_ = 0xa2005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fltq.d";
    };
    {
      mnemonic = "fmaxm.d";
      mask = 0xfe00707fL;
      match_ = 0x2a003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fmaxm.d";
    };
    {
      mnemonic = "fminm.d";
      mask = 0xfe00707fL;
      match_ = 0x2a002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_d_zfa/fminm.d";
    };
    {
      mnemonic = "fleq.s";
      mask = 0xfe00707fL;
      match_ = 0xa0004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fleq.s";
    };
    {
      mnemonic = "fltq.s";
      mask = 0xfe00707fL;
      match_ = 0xa0005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fltq.s";
    };
    {
      mnemonic = "fmaxm.s";
      mask = 0xfe00707fL;
      match_ = 0x28003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fmaxm.s";
    };
    {
      mnemonic = "fminm.s";
      mask = 0xfe00707fL;
      match_ = 0x28002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_f_zfa/fminm.s";
    };
    {
      mnemonic = "feq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6002053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/feq.q";
    };
    {
      mnemonic = "fle.q";
      mask = 0xfe00707fL;
      match_ = 0xa6000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fle.q";
    };
    {
      mnemonic = "flt.q";
      mask = 0xfe00707fL;
      match_ = 0xa6001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/flt.q";
    };
    {
      mnemonic = "fmax.q";
      mask = 0xfe00707fL;
      match_ = 0x2e001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmax.q";
    };
    {
      mnemonic = "fmin.q";
      mask = 0xfe00707fL;
      match_ = 0x2e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmin.q";
    };
    {
      mnemonic = "fsgnj.q";
      mask = 0xfe00707fL;
      match_ = 0x26000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnj.q";
    };
    {
      mnemonic = "fsgnjn.q";
      mask = 0xfe00707fL;
      match_ = 0x26001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnjn.q";
    };
    {
      mnemonic = "fsgnjx.q";
      mask = 0xfe00707fL;
      match_ = 0x26002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsgnjx.q";
    };
    {
      mnemonic = "fleq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fleq.q";
    };
    {
      mnemonic = "fltq.q";
      mask = 0xfe00707fL;
      match_ = 0xa6005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fltq.q";
    };
    {
      mnemonic = "fmaxm.q";
      mask = 0xfe00707fL;
      match_ = 0x2e003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fmaxm.q";
    };
    {
      mnemonic = "fminm.q";
      mask = 0xfe00707fL;
      match_ = 0x2e002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_q_zfa/fminm.q";
    };
    {
      mnemonic = "amoadd.b";
      mask = 0xfe00707fL;
      match_ = 0x2fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.b";
    };
    {
      mnemonic = "amoadd.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.b";
    };
    {
      mnemonic = "amoadd.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.b";
    };
    {
      mnemonic = "amoadd.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.b";
    };
    {
      mnemonic = "amoadd.h";
      mask = 0xfe00707fL;
      match_ = 0x102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.h";
    };
    {
      mnemonic = "amoadd.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.h";
    };
    {
      mnemonic = "amoadd.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.h";
    };
    {
      mnemonic = "amoadd.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoadd.h";
    };
    {
      mnemonic = "amoand.b";
      mask = 0xfe00707fL;
      match_ = 0x6000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.b";
    };
    {
      mnemonic = "amoand.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x6400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.b";
    };
    {
      mnemonic = "amoand.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x6200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.b";
    };
    {
      mnemonic = "amoand.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x6600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.b";
    };
    {
      mnemonic = "amoand.h";
      mask = 0xfe00707fL;
      match_ = 0x6000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.h";
    };
    {
      mnemonic = "amoand.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x6400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.h";
    };
    {
      mnemonic = "amoand.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x6200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.h";
    };
    {
      mnemonic = "amoand.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x6600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoand.h";
    };
    {
      mnemonic = "amomax.b";
      mask = 0xfe00707fL;
      match_ = 0xa000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.b";
    };
    {
      mnemonic = "amomax.b.aq";
      mask = 0xfe00707fL;
      match_ = 0xa400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.b";
    };
    {
      mnemonic = "amomax.b.rl";
      mask = 0xfe00707fL;
      match_ = 0xa200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.b";
    };
    {
      mnemonic = "amomax.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xa600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.b";
    };
    {
      mnemonic = "amomax.h";
      mask = 0xfe00707fL;
      match_ = 0xa000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.h";
    };
    {
      mnemonic = "amomax.h.aq";
      mask = 0xfe00707fL;
      match_ = 0xa400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.h";
    };
    {
      mnemonic = "amomax.h.rl";
      mask = 0xfe00707fL;
      match_ = 0xa200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.h";
    };
    {
      mnemonic = "amomax.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xa600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomax.h";
    };
    {
      mnemonic = "amomaxu.b";
      mask = 0xfe00707fL;
      match_ = 0xe000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.b";
    };
    {
      mnemonic = "amomaxu.b.aq";
      mask = 0xfe00707fL;
      match_ = 0xe400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.b";
    };
    {
      mnemonic = "amomaxu.b.rl";
      mask = 0xfe00707fL;
      match_ = 0xe200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.b";
    };
    {
      mnemonic = "amomaxu.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xe600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.b";
    };
    {
      mnemonic = "amomaxu.h";
      mask = 0xfe00707fL;
      match_ = 0xe000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.h";
    };
    {
      mnemonic = "amomaxu.h.aq";
      mask = 0xfe00707fL;
      match_ = 0xe400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.h";
    };
    {
      mnemonic = "amomaxu.h.rl";
      mask = 0xfe00707fL;
      match_ = 0xe200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.h";
    };
    {
      mnemonic = "amomaxu.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xe600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomaxu.h";
    };
    {
      mnemonic = "amomin.b";
      mask = 0xfe00707fL;
      match_ = 0x8000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.b";
    };
    {
      mnemonic = "amomin.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x8400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.b";
    };
    {
      mnemonic = "amomin.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x8200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.b";
    };
    {
      mnemonic = "amomin.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x8600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.b";
    };
    {
      mnemonic = "amomin.h";
      mask = 0xfe00707fL;
      match_ = 0x8000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.h";
    };
    {
      mnemonic = "amomin.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x8400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.h";
    };
    {
      mnemonic = "amomin.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x8200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.h";
    };
    {
      mnemonic = "amomin.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x8600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amomin.h";
    };
    {
      mnemonic = "amominu.b";
      mask = 0xfe00707fL;
      match_ = 0xc000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.b";
    };
    {
      mnemonic = "amominu.b.aq";
      mask = 0xfe00707fL;
      match_ = 0xc400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.b";
    };
    {
      mnemonic = "amominu.b.rl";
      mask = 0xfe00707fL;
      match_ = 0xc200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.b";
    };
    {
      mnemonic = "amominu.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xc600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.b";
    };
    {
      mnemonic = "amominu.h";
      mask = 0xfe00707fL;
      match_ = 0xc000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.h";
    };
    {
      mnemonic = "amominu.h.aq";
      mask = 0xfe00707fL;
      match_ = 0xc400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.h";
    };
    {
      mnemonic = "amominu.h.rl";
      mask = 0xfe00707fL;
      match_ = 0xc200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.h";
    };
    {
      mnemonic = "amominu.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xc600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amominu.h";
    };
    {
      mnemonic = "amoor.b";
      mask = 0xfe00707fL;
      match_ = 0x4000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.b";
    };
    {
      mnemonic = "amoor.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x4400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.b";
    };
    {
      mnemonic = "amoor.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x4200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.b";
    };
    {
      mnemonic = "amoor.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x4600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.b";
    };
    {
      mnemonic = "amoor.h";
      mask = 0xfe00707fL;
      match_ = 0x4000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.h";
    };
    {
      mnemonic = "amoor.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x4400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.h";
    };
    {
      mnemonic = "amoor.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x4200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.h";
    };
    {
      mnemonic = "amoor.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x4600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoor.h";
    };
    {
      mnemonic = "amoswap.b";
      mask = 0xfe00707fL;
      match_ = 0x800002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.b";
    };
    {
      mnemonic = "amoswap.b.aq";
      mask = 0xfe00707fL;
      match_ = 0xc00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.b";
    };
    {
      mnemonic = "amoswap.b.rl";
      mask = 0xfe00707fL;
      match_ = 0xa00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.b";
    };
    {
      mnemonic = "amoswap.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xe00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.b";
    };
    {
      mnemonic = "amoswap.h";
      mask = 0xfe00707fL;
      match_ = 0x800102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.h";
    };
    {
      mnemonic = "amoswap.h.aq";
      mask = 0xfe00707fL;
      match_ = 0xc00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.h";
    };
    {
      mnemonic = "amoswap.h.rl";
      mask = 0xfe00707fL;
      match_ = 0xa00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.h";
    };
    {
      mnemonic = "amoswap.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0xe00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoswap.h";
    };
    {
      mnemonic = "amoxor.b";
      mask = 0xfe00707fL;
      match_ = 0x2000002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.b";
    };
    {
      mnemonic = "amoxor.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x2400002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.b";
    };
    {
      mnemonic = "amoxor.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x2200002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.b";
    };
    {
      mnemonic = "amoxor.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2600002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.b";
    };
    {
      mnemonic = "amoxor.h";
      mask = 0xfe00707fL;
      match_ = 0x2000102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.h";
    };
    {
      mnemonic = "amoxor.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x2400102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.h";
    };
    {
      mnemonic = "amoxor.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x2200102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.h";
    };
    {
      mnemonic = "amoxor.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2600102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zabha";
      source = "rv_zabha/amoxor.h";
    };
    {
      mnemonic = "amocas.b";
      mask = 0xfe00707fL;
      match_ = 0x2800002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.b";
    };
    {
      mnemonic = "amocas.b.aq";
      mask = 0xfe00707fL;
      match_ = 0x2c00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.b";
    };
    {
      mnemonic = "amocas.b.rl";
      mask = 0xfe00707fL;
      match_ = 0x2a00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.b";
    };
    {
      mnemonic = "amocas.b.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2e00002fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.b";
    };
    {
      mnemonic = "amocas.h";
      mask = 0xfe00707fL;
      match_ = 0x2800102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.h";
    };
    {
      mnemonic = "amocas.h.aq";
      mask = 0xfe00707fL;
      match_ = 0x2c00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.h";
    };
    {
      mnemonic = "amocas.h.rl";
      mask = 0xfe00707fL;
      match_ = 0x2a00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.h";
    };
    {
      mnemonic = "amocas.h.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2e00102fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zabha_zacas/amocas.h";
    };
    {
      mnemonic = "amocas.d";
      mask = 0xfe00707fL;
      match_ = 0x2800302fL;
      operands = [ Gpr_pair { lsb = 7; below = 64 }; Gpr_pair { lsb = 20; below = 64 }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.d";
    };
    {
      mnemonic = "amocas.d.aq";
      mask = 0xfe00707fL;
      match_ = 0x2c00302fL;
      operands = [ Gpr_pair { lsb = 7; below = 64 }; Gpr_pair { lsb = 20; below = 64 }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.d";
    };
    {
      mnemonic = "amocas.d.rl";
      mask = 0xfe00707fL;
      match_ = 0x2a00302fL;
      operands = [ Gpr_pair { lsb = 7; below = 64 }; Gpr_pair { lsb = 20; below = 64 }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.d";
    };
    {
      mnemonic = "amocas.d.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2e00302fL;
      operands = [ Gpr_pair { lsb = 7; below = 64 }; Gpr_pair { lsb = 20; below = 64 }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.d";
    };
    {
      mnemonic = "amocas.w";
      mask = 0xfe00707fL;
      match_ = 0x2800202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.w";
    };
    {
      mnemonic = "amocas.w.aq";
      mask = 0xfe00707fL;
      match_ = 0x2c00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.w";
    };
    {
      mnemonic = "amocas.w.rl";
      mask = 0xfe00707fL;
      match_ = 0x2a00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.w";
    };
    {
      mnemonic = "amocas.w.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x2e00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zacas";
      source = "rv_zacas/amocas.w";
    };
    {
      mnemonic = "feq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4002053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/feq.h";
    };
    {
      mnemonic = "fle.h";
      mask = 0xfe00707fL;
      match_ = 0xa4000053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fle.h";
    };
    {
      mnemonic = "flt.h";
      mask = 0xfe00707fL;
      match_ = 0xa4001053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/flt.h";
    };
    {
      mnemonic = "fmax.h";
      mask = 0xfe00707fL;
      match_ = 0x2c001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmax.h";
    };
    {
      mnemonic = "fmin.h";
      mask = 0xfe00707fL;
      match_ = 0x2c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmin.h";
    };
    {
      mnemonic = "fsgnj.h";
      mask = 0xfe00707fL;
      match_ = 0x24000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnj.h";
    };
    {
      mnemonic = "fsgnjn.h";
      mask = 0xfe00707fL;
      match_ = 0x24001053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnjn.h";
    };
    {
      mnemonic = "fsgnjx.h";
      mask = 0xfe00707fL;
      match_ = 0x24002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsgnjx.h";
    };
    {
      mnemonic = "fleq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4004053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fleq.h";
    };
    {
      mnemonic = "fltq.h";
      mask = 0xfe00707fL;
      match_ = 0xa4005053L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fltq.h";
    };
    {
      mnemonic = "fmaxm.h";
      mask = 0xfe00707fL;
      match_ = 0x2c003053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fmaxm.h";
    };
    {
      mnemonic = "fminm.h";
      mask = 0xfe00707fL;
      match_ = 0x2c002053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 } ];
      xlen = 0;
      feature = "zfa";
      source = "rv_zfh_zfa/fminm.h";
    };
    {
      mnemonic = "ssamoswap.d";
      mask = 0xfe00707fL;
      match_ = 0x4800302fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.d";
    };
    {
      mnemonic = "ssamoswap.d.aq";
      mask = 0xfe00707fL;
      match_ = 0x4c00302fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.d";
    };
    {
      mnemonic = "ssamoswap.d.rl";
      mask = 0xfe00707fL;
      match_ = 0x4a00302fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.d";
    };
    {
      mnemonic = "ssamoswap.d.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x4e00302fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.d";
    };
    {
      mnemonic = "ssamoswap.w";
      mask = 0xfe00707fL;
      match_ = 0x4800202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.w";
    };
    {
      mnemonic = "ssamoswap.w.aq";
      mask = 0xfe00707fL;
      match_ = 0x4c00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.w";
    };
    {
      mnemonic = "ssamoswap.w.rl";
      mask = 0xfe00707fL;
      match_ = 0x4a00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.w";
    };
    {
      mnemonic = "ssamoswap.w.aqrl";
      mask = 0xfe00707fL;
      match_ = 0x4e00202fL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 20; nonzero = false }; Mem_zero { base = 15 } ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_zicfiss/ssamoswap.w";
    };
    {
      mnemonic = "mop.rr.0";
      mask = 0xfe00707fL;
      match_ = 0x82004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.0";
    };
    {
      mnemonic = "mop.rr.1";
      mask = 0xfe00707fL;
      match_ = 0x86004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.1";
    };
    {
      mnemonic = "mop.rr.2";
      mask = 0xfe00707fL;
      match_ = 0x8a004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.2";
    };
    {
      mnemonic = "mop.rr.3";
      mask = 0xfe00707fL;
      match_ = 0x8e004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.3";
    };
    {
      mnemonic = "mop.rr.4";
      mask = 0xfe00707fL;
      match_ = 0xc2004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.4";
    };
    {
      mnemonic = "mop.rr.5";
      mask = 0xfe00707fL;
      match_ = 0xc6004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.5";
    };
    {
      mnemonic = "mop.rr.6";
      mask = 0xfe00707fL;
      match_ = 0xca004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.6";
    };
    {
      mnemonic = "mop.rr.7";
      mask = 0xfe00707fL;
      match_ = 0xce004073L;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 0;
      feature = "zimop";
      source = "rv_zimop/mop.rr.7";
    };
    {
      mnemonic = "fmvp.d.x";
      mask = 0xfe00707fL;
      match_ = 0xb2000053L;
      operands = [ Fpr { lsb = 7 }; Gpr { lsb = 15; nonzero = false }; Gpr { lsb = 20; nonzero = false } ];
      xlen = 32;
      feature = "zfa";
      source = "rv32_d_zfa/fmvp.d.x";
    };
    {
      mnemonic = "slli.uw";
      mask = 0xfc00707fL;
      match_ = 0x800101bL;
      operands = [ Gpr { lsb = 7; nonzero = false }; Gpr { lsb = 15; nonzero = false }; Uimm { lsb = 20; width = 6 } ];
      xlen = 64;
      feature = "zba";
      source = "rv64_zba/slli.uw";
    };
    {
      mnemonic = "c.nop";
      mask = 0xffffL;
      match_ = 0x1L;
      operands = [  ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.nop";
    };
    {
      mnemonic = "c.sspopchk";
      mask = 0xffffL;
      match_ = 0x6281L;
      operands = [ Fixed_gpr 5 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_c_zicfiss/c.sspopchk.x5";
    };
    {
      mnemonic = "c.sspush";
      mask = 0xffffL;
      match_ = 0x6081L;
      operands = [ Fixed_gpr 1 ];
      xlen = 0;
      feature = "zicfiss";
      source = "rv_c_zicfiss/c.sspush.x1";
    };
    {
      mnemonic = "c.ntl.all";
      mask = 0xffffL;
      match_ = 0x9016L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_c_zihintntl/c.ntl.all";
    };
    {
      mnemonic = "c.ntl.p1";
      mask = 0xffffL;
      match_ = 0x900aL;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_c_zihintntl/c.ntl.p1";
    };
    {
      mnemonic = "c.ntl.pall";
      mask = 0xffffL;
      match_ = 0x900eL;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_c_zihintntl/c.ntl.pall";
    };
    {
      mnemonic = "c.ntl.s1";
      mask = 0xffffL;
      match_ = 0x9012L;
      operands = [  ];
      xlen = 0;
      feature = "zihintntl";
      source = "rv_c_zihintntl/c.ntl.s1";
    };
    {
      mnemonic = "c.mop.11";
      mask = 0xffffL;
      match_ = 0x6581L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.11";
    };
    {
      mnemonic = "c.mop.13";
      mask = 0xffffL;
      match_ = 0x6681L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.13";
    };
    {
      mnemonic = "c.mop.15";
      mask = 0xffffL;
      match_ = 0x6781L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.15";
    };
    {
      mnemonic = "c.mop.1";
      mask = 0xffffL;
      match_ = 0x6081L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.1";
    };
    {
      mnemonic = "c.mop.3";
      mask = 0xffffL;
      match_ = 0x6181L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.3";
    };
    {
      mnemonic = "c.mop.5";
      mask = 0xffffL;
      match_ = 0x6281L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.5";
    };
    {
      mnemonic = "c.mop.7";
      mask = 0xffffL;
      match_ = 0x6381L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.7";
    };
    {
      mnemonic = "c.mop.9";
      mask = 0xffffL;
      match_ = 0x6481L;
      operands = [  ];
      xlen = 0;
      feature = "zcmop";
      source = "rv_zcmop/c.mop.9";
    };
    {
      mnemonic = "fadd.q";
      mask = 0xfe00007fL;
      match_ = 0x6000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fadd.q";
    };
    {
      mnemonic = "fdiv.q";
      mask = 0xfe00007fL;
      match_ = 0x1e000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fdiv.q";
    };
    {
      mnemonic = "fmul.q";
      mask = 0xfe00007fL;
      match_ = 0x16000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmul.q";
    };
    {
      mnemonic = "fsub.q";
      mask = 0xfe00007fL;
      match_ = 0xe000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsub.q";
    };
    {
      mnemonic = "fadd.h";
      mask = 0xfe00007fL;
      match_ = 0x4000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fadd.h";
    };
    {
      mnemonic = "fdiv.h";
      mask = 0xfe00007fL;
      match_ = 0x1c000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fdiv.h";
    };
    {
      mnemonic = "fmul.h";
      mask = 0xfe00007fL;
      match_ = 0x14000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmul.h";
    };
    {
      mnemonic = "fsub.h";
      mask = 0xfe00007fL;
      match_ = 0xc000053L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fsub.h";
    };
    {
      mnemonic = "c.zext.w";
      mask = 0xfc7fL;
      match_ = 0x9c71L;
      operands = [ Creg { lsb = 7 } ];
      xlen = 64;
      feature = "zcb";
      source = "rv64_zcb/c.zext.w";
    };
    {
      mnemonic = "c.not";
      mask = 0xfc7fL;
      match_ = 0x9c75L;
      operands = [ Creg { lsb = 7 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.not";
    };
    {
      mnemonic = "c.sext.b";
      mask = 0xfc7fL;
      match_ = 0x9c65L;
      operands = [ Creg { lsb = 7 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.sext.b";
    };
    {
      mnemonic = "c.sext.h";
      mask = 0xfc7fL;
      match_ = 0x9c6dL;
      operands = [ Creg { lsb = 7 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.sext.h";
    };
    {
      mnemonic = "c.zext.b";
      mask = 0xfc7fL;
      match_ = 0x9c61L;
      operands = [ Creg { lsb = 7 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.zext.b";
    };
    {
      mnemonic = "c.zext.h";
      mask = 0xfc7fL;
      match_ = 0x9c69L;
      operands = [ Creg { lsb = 7 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.zext.h";
    };
    {
      mnemonic = "lpad";
      mask = 0xfffL;
      match_ = 0x17L;
      operands = [ Uimm { lsb = 12; width = 20 } ];
      xlen = 0;
      feature = "zicfilp";
      source = "rv_zicfilp/lpad";
    };
    {
      mnemonic = "c.sext.w";
      mask = 0xf07fL;
      match_ = 0x2001L;
      operands = [ Gpr { lsb = 7; nonzero = true } ];
      xlen = 64;
      feature = "zcb";
      source = "rv64_zcb/c.sext.w";
    };
    {
      mnemonic = "c.addi16sp";
      mask = 0xef83L;
      match_ = 0x6101L;
      operands = [ Fixed_gpr 2; Scatter { signed = true; nonzero = true; scale = 4; width = 10; bits = [ (12, 9); (6, 4); (5, 6); (4, 8); (3, 7); (2, 5) ] } ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.addi16sp";
    };
    {
      mnemonic = "flq";
      mask = 0x707fL;
      match_ = 0x4007L;
      operands = [ Fpr { lsb = 7 }; Mem_i { base = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/flq";
    };
    {
      mnemonic = "fsq";
      mask = 0x707fL;
      match_ = 0x4027L;
      operands = [ Fpr { lsb = 20 }; Mem_s { base = 15 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fsq";
    };
    {
      mnemonic = "c.mul";
      mask = 0xfc63L;
      match_ = 0x9c41L;
      operands = [ Creg { lsb = 7 }; Creg { lsb = 2 } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.mul";
    };
    {
      mnemonic = "cm.mva01s";
      mask = 0xfc63L;
      match_ = 0xac62L;
      operands = [ Sreg { lsb = 7 }; Sreg { lsb = 2 } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.mva01s";
    };
    {
      mnemonic = "cm.mvsa01";
      mask = 0xfc63L;
      match_ = 0xac22L;
      operands = [ Sreg { lsb = 7 }; Sreg { lsb = 2 } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.mvsa01";
    };
    {
      mnemonic = "cm.pop";
      mask = 0xff03L;
      match_ = 0xba02L;
      operands = [ Rlist { lsb = 4 }; Stack_adj { rlist = 4; spimm = 2; push = false } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.pop";
    };
    {
      mnemonic = "cm.popret";
      mask = 0xff03L;
      match_ = 0xbe02L;
      operands = [ Rlist { lsb = 4 }; Stack_adj { rlist = 4; spimm = 2; push = false } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.popret";
    };
    {
      mnemonic = "cm.popretz";
      mask = 0xff03L;
      match_ = 0xbc02L;
      operands = [ Rlist { lsb = 4 }; Stack_adj { rlist = 4; spimm = 2; push = false } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.popretz";
    };
    {
      mnemonic = "cm.push";
      mask = 0xff03L;
      match_ = 0xb802L;
      operands = [ Rlist { lsb = 4 }; Stack_adj { rlist = 4; spimm = 2; push = true } ];
      xlen = 0;
      feature = "zcmp";
      source = "rv_zcmp/cm.push";
    };
    {
      mnemonic = "flh";
      mask = 0x707fL;
      match_ = 0x1007L;
      operands = [ Fpr { lsb = 7 }; Mem_i { base = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/flh";
    };
    {
      mnemonic = "fsh";
      mask = 0x707fL;
      match_ = 0x1027L;
      operands = [ Fpr { lsb = 20 }; Mem_s { base = 15 } ];
      xlen = 0;
      feature = "zfhmin";
      source = "rv_zfhmin/fsh";
    };
    {
      mnemonic = "fmadd.q";
      mask = 0x600007fL;
      match_ = 0x6000043L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmadd.q";
    };
    {
      mnemonic = "fmsub.q";
      mask = 0x600007fL;
      match_ = 0x6000047L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fmsub.q";
    };
    {
      mnemonic = "fnmadd.q";
      mask = 0x600007fL;
      match_ = 0x600004fL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fnmadd.q";
    };
    {
      mnemonic = "fnmsub.q";
      mask = 0x600007fL;
      match_ = 0x600004bL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "q";
      source = "rv_q/fnmsub.q";
    };
    {
      mnemonic = "c.lh";
      mask = 0xfc43L;
      match_ = 0x8440L;
      operands = [ Creg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 1; width = 2; bits = [ (5, 1) ] } } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.lh";
    };
    {
      mnemonic = "c.lhu";
      mask = 0xfc43L;
      match_ = 0x8400L;
      operands = [ Creg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 1; width = 2; bits = [ (5, 1) ] } } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.lhu";
    };
    {
      mnemonic = "c.sh";
      mask = 0xfc43L;
      match_ = 0x8c00L;
      operands = [ Creg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 1; width = 2; bits = [ (5, 1) ] } } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.sh";
    };
    {
      mnemonic = "fmadd.h";
      mask = 0x600007fL;
      match_ = 0x4000043L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmadd.h";
    };
    {
      mnemonic = "fmsub.h";
      mask = 0x600007fL;
      match_ = 0x4000047L;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fmsub.h";
    };
    {
      mnemonic = "fnmadd.h";
      mask = 0x600007fL;
      match_ = 0x400004fL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fnmadd.h";
    };
    {
      mnemonic = "fnmsub.h";
      mask = 0x600007fL;
      match_ = 0x400004bL;
      operands = [ Fpr { lsb = 7 }; Fpr { lsb = 15 }; Fpr { lsb = 20 }; Fpr { lsb = 27 }; Rm { lsb = 12; default = 7 } ];
      xlen = 0;
      feature = "zfh";
      source = "rv_zfh/fnmsub.h";
    };
    {
      mnemonic = "c.lbu";
      mask = 0xfc03L;
      match_ = 0x8000L;
      operands = [ Creg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 0; width = 2; bits = [ (6, 0); (5, 1) ] } } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.lbu";
    };
    {
      mnemonic = "c.sb";
      mask = 0xfc03L;
      match_ = 0x8800L;
      operands = [ Creg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 0; width = 2; bits = [ (6, 0); (5, 1) ] } } ];
      xlen = 0;
      feature = "zcb";
      source = "rv_zcb/c.sb";
    };
    {
      mnemonic = "cm.jalt";
      mask = 0xfc03L;
      match_ = 0xa002L;
      operands = [ Uimm_min { lsb = 2; width = 8; min = 32 } ];
      xlen = 0;
      feature = "zcmt";
      source = "rv_zcmt/cm.jalt";
    };
    {
      mnemonic = "c.srai";
      mask = 0xfc03L;
      match_ = 0x8401L;
      operands = [ Creg { lsb = 7 }; Scatter { signed = false; nonzero = true; scale = 0; width = 5; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0) ] } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c/c.srai";
    };
    {
      mnemonic = "c.srli";
      mask = 0xfc03L;
      match_ = 0x8001L;
      operands = [ Creg { lsb = 7 }; Scatter { signed = false; nonzero = true; scale = 0; width = 5; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0) ] } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c/c.srli";
    };
    {
      mnemonic = "c.srai";
      mask = 0xec03L;
      match_ = 0x8401L;
      operands = [ Creg { lsb = 7 }; Scatter { signed = false; nonzero = true; scale = 0; width = 6; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0); (12, 5) ] } ];
      xlen = 64;
      feature = "c";
      source = "rv64_c/c.srai";
    };
    {
      mnemonic = "c.srli";
      mask = 0xec03L;
      match_ = 0x8001L;
      operands = [ Creg { lsb = 7 }; Scatter { signed = false; nonzero = true; scale = 0; width = 6; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0); (12, 5) ] } ];
      xlen = 64;
      feature = "c";
      source = "rv64_c/c.srli";
    };
    {
      mnemonic = "c.andi";
      mask = 0xec03L;
      match_ = 0x8801L;
      operands = [ Creg { lsb = 7 }; Scatter { signed = true; nonzero = false; scale = 0; width = 6; bits = [ (12, 5); (6, 4); (5, 3); (4, 2); (3, 1); (2, 0) ] } ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.andi";
    };
    {
      mnemonic = "c.slli";
      mask = 0xf003L;
      match_ = 0x2L;
      operands = [ Gpr { lsb = 7; nonzero = true }; Scatter { signed = false; nonzero = true; scale = 0; width = 5; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0) ] } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c/c.slli";
    };
    {
      mnemonic = "c.addiw";
      mask = 0xe003L;
      match_ = 0x2001L;
      operands = [ Gpr { lsb = 7; nonzero = true }; Scatter { signed = true; nonzero = false; scale = 0; width = 6; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0); (12, 5) ] } ];
      xlen = 64;
      feature = "c";
      source = "rv64_c/c.addiw";
    };
    {
      mnemonic = "c.slli";
      mask = 0xe003L;
      match_ = 0x2L;
      operands = [ Gpr { lsb = 7; nonzero = true }; Scatter { signed = false; nonzero = true; scale = 0; width = 6; bits = [ (12, 5); (6, 4); (5, 3); (4, 2); (3, 1); (2, 0) ] } ];
      xlen = 64;
      feature = "c";
      source = "rv64_c/c.slli";
    };
    {
      mnemonic = "c.addi4spn";
      mask = 0xe003L;
      match_ = 0x0L;
      operands = [ Creg { lsb = 2 }; Fixed_gpr 2; Scatter { signed = false; nonzero = true; scale = 2; width = 10; bits = [ (12, 5); (11, 4); (10, 9); (9, 8); (8, 7); (7, 6); (6, 2); (5, 3) ] } ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.addi4spn";
    };
    {
      mnemonic = "c.li";
      mask = 0xe003L;
      match_ = 0x4001L;
      operands = [ Gpr { lsb = 7; nonzero = true }; Scatter { signed = true; nonzero = false; scale = 0; width = 6; bits = [ (6, 4); (5, 3); (4, 2); (3, 1); (2, 0); (12, 5) ] } ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.li";
    };
    {
      mnemonic = "c.lui";
      mask = 0xe003L;
      match_ = 0x6001L;
      operands = [ Gpr_except { lsb = 7; except = [ 0; 2 ] }; Cui { hi = 12; lo = 2 } ];
      xlen = 0;
      feature = "c";
      source = "rv_c/c.lui";
    };
    {
      mnemonic = "c.fld";
      mask = 0xe003L;
      match_ = 0x2000L;
      operands = [ Cfreg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 3; width = 8; bits = [ (6, 7); (5, 6); (12, 5); (11, 4); (10, 3) ] } } ];
      xlen = 0;
      feature = "c";
      source = "rv_c_d/c.fld";
    };
    {
      mnemonic = "c.fldsp";
      mask = 0xe003L;
      match_ = 0x2002L;
      operands = [ Fpr { lsb = 7 }; Spmem { offset = { signed = false; nonzero = false; scale = 3; width = 9; bits = [ (12, 5); (6, 4); (5, 3); (4, 8); (3, 7); (2, 6) ] } } ];
      xlen = 0;
      feature = "c";
      source = "rv_c_d/c.fldsp";
    };
    {
      mnemonic = "c.fsd";
      mask = 0xe003L;
      match_ = 0xa000L;
      operands = [ Cfreg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 3; width = 8; bits = [ (6, 7); (5, 6); (12, 5); (11, 4); (10, 3) ] } } ];
      xlen = 0;
      feature = "c";
      source = "rv_c_d/c.fsd";
    };
    {
      mnemonic = "c.fsdsp";
      mask = 0xe003L;
      match_ = 0xa002L;
      operands = [ Fpr { lsb = 2 }; Spmem { offset = { signed = false; nonzero = false; scale = 3; width = 9; bits = [ (12, 5); (11, 4); (10, 3); (9, 8); (8, 7); (7, 6) ] } } ];
      xlen = 0;
      feature = "c";
      source = "rv_c_d/c.fsdsp";
    };
    {
      mnemonic = "c.flw";
      mask = 0xe003L;
      match_ = 0x6000L;
      operands = [ Cfreg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 2; width = 7; bits = [ (6, 2); (5, 6); (12, 5); (11, 4); (10, 3) ] } } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c_f/c.flw";
    };
    {
      mnemonic = "c.flwsp";
      mask = 0xe003L;
      match_ = 0x6002L;
      operands = [ Fpr { lsb = 7 }; Spmem { offset = { signed = false; nonzero = false; scale = 2; width = 8; bits = [ (12, 5); (6, 4); (5, 3); (4, 2); (3, 7); (2, 6) ] } } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c_f/c.flwsp";
    };
    {
      mnemonic = "c.fsw";
      mask = 0xe003L;
      match_ = 0xe000L;
      operands = [ Cfreg { lsb = 2 }; Cmem { base = 7; offset = { signed = false; nonzero = false; scale = 2; width = 7; bits = [ (6, 2); (5, 6); (12, 5); (11, 4); (10, 3) ] } } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c_f/c.fsw";
    };
    {
      mnemonic = "c.fswsp";
      mask = 0xe003L;
      match_ = 0xe002L;
      operands = [ Fpr { lsb = 2 }; Spmem { offset = { signed = false; nonzero = false; scale = 2; width = 8; bits = [ (12, 5); (11, 4); (10, 3); (9, 2); (8, 7); (7, 6) ] } } ];
      xlen = 32;
      feature = "c";
      source = "rv32_c_f/c.fswsp";
    };
  |]
