(library
 (name riscv64_encode)
 (public_name rivet.riscv64_encode)
 (modules riscv64_encode)
 (modes byte native)
 (libraries
  foundation
  codec
  asm_core
  target_error
  target_encode
  riscv_family_encode)
 (enabled_if
  (<> %{env:RIVET_MELANGE=false} true)))

(library
 (name riscv64)
 (public_name rivet.riscv64)
 (modules riscv64)
 (modes byte native)
 (libraries
  foundation
  codec
  asm_core
  asm_syntax
  target_intf
  riscv_family
  riscv64_encode)
 (enabled_if
  (<> %{env:RIVET_MELANGE=false} true)))
